apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: headers-vs
spec:
  hosts:
    - "*"
  gateways:
    - headers-gateway
  http:
    - match:
        - uri:
            prefix: /headers
      rewrite:
        uri: /
      route:
        - destination:
            host: headers
            port:
              number: 8080